//! Gallery folder renaming pipeline: `<gid>-<sanitized title>` -> `[Author] Title`.
//!
//! The rename is derived from the single source of truth (`title`, stored with
//! brackets intact) plus metadata captured at download time (`artist`, `group`,
//! `language`). A configurable blocklist strips useless tags (language /
//! translator / AI / Patreon / Pixiv / Unifans...) and leters remain as the work
//! name. Author resolution: leading `[....]` bracket -> metadata `artist` ->
//! metadata `group` -> `uploader` (already folded into `artist` at capture).

use std::fmt;

/// A rename that cannot be produced (the gallery is left untouched).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RenameSkip {
    /// No author could be identified: no leading `[bracket]`, no artist metadata.
    NoAuthor,
    /// After tag filtering the work title became empty.
    EmptyTitle,
}

impl fmt::Display for RenameSkip {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            RenameSkip::NoAuthor => write!(f, "无法识别作者名"),
            RenameSkip::EmptyTitle => write!(f, "作品名为空"),
        }
    }
}

/// One renamed (or skipped / failed) gallery entry, returned to the UI for both
/// the preview and the execution report.
#[derive(Debug, Clone, Default, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RenameEntry {
    pub gid: u64,
    /// Pre-rename folder basename, e.g. `1234567-My Gallery_ Volume 1`.
    pub old_name: String,
    /// Post-rename folder basename, e.g. `[Author Name] My Gallery Volume 1`.
    pub new_name: String,
    /// `renamed` | `skipped` | `failed`.
    pub status: String,
    /// Human-readable reason for skipped / failed entries.
    pub reason: Option<String>,
}

/// Aggregate result of a preview or an execution run.
#[derive(Debug, Clone, Default, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RenameReport {
    pub entries: Vec<RenameEntry>,
    pub renamed: usize,
    pub skipped: usize,
    pub failed: usize,
}

/// Default blocklist of useless title tags. Users may override it through the
/// `rename_filter_terms` setting; an empty list falls back to this one.
pub fn default_filter_terms() -> Vec<String> {
    [
        // Languages (names + common abbreviations).
        "chinese", "english", "japanese", "korean", "french", "german", "spanish",
        "russian", "italian", "portuguese", "dutch", "taiwanese", "polish", "thai",
        "vietnamese", "chn", "eng", "jpn", "zh", "cn", "jp", "kr",
        "中文", "简体", "簡體", "繁体", "繁體", "简中", "繁中", "英语", "日语", "韩语",
        "中译", "中英", "日中",
        // Translator / scanlation labels.
        "translat", "scanlat", "汉化", "翻译", "翻訳", "简翻",
        // AI-generated labels.
        "ai generated", "ai", "aigenerated", "autogenerated", "midjourney",
        "stable diffusion", "novelai", "kobold",
        // Platform / commissioning tags.
        "patreon", "patron", "pixiv", "pivix", "fanbox", "ko-fi", "kofi",
        "unifans", "fantia", "subscribe",
        // Miscellaneous display tags.
        "digital", "dl", "dl版", "full color", "fullcolour", "fullcolor",
        "webtoon", "crop", "no text", "textless",
    ]
    .iter()
    .map(|s| s.to_string())
    .collect()
}

/// Parses the gallery folder basename `<gid>-<the rest>` back into `(gid, rest)`.
/// Only an all-digit 6-9 char prefix (matches SXJ `\d{7,8}` gids) is accepted.
pub fn parse_old_folder_name(name: &str) -> Option<(u64, &str)> {
    let dash = name.find('-')?;
    let prefix = &name[..dash];
    if prefix.is_empty()
        || !(6..=9).contains(&prefix.len())
        || !prefix.chars().all(|c| c.is_ascii_digit())
    {
        return None;
    }
    let gid: u64 = prefix.parse().ok()?;
    if gid == 0 {
        return None;
    }
    Some((gid, &name[dash + 1..]))
}

/// Computes the new folder name `[Author] Title`, or the reason it cannot be
/// produced. `title` is the raw stored gallery title (brackets intact).
pub fn plan_rename(
    title: &str,
    artist: Option<&str>,
    language: Option<&str>,
    terms: &[String],
) -> Result<String, RenameSkip> {
    let (bracket_author, rest) = take_leading_bracket(title);
    // A leading bracket is only the author when it is *not* itself a useless tag
    // (e.g. `[Chinese] Title`); otherwise it is filtered like any other tag.
    let bracket_is_author = bracket_author
        .as_ref()
        .is_some_and(|b| !is_blocked(b, language, terms));

    let candidate = if bracket_is_author {
        bracket_author.clone()
    } else {
        artist.map(str::to_string)
    };
    let author_raw = candidate.map(|s| s.trim().to_string()).filter(|s| !s.is_empty());
    let author_raw = author_raw.ok_or(RenameSkip::NoAuthor)?;

    let base_title = if bracket_is_author {
        rest
    } else {
        title.to_string()
    };
    let cleaned = strip_blocked_brackets(&base_title, language, terms);
    let title_safe = to_folder_name(&cleaned);
    if title_safe.is_empty() {
        return Err(RenameSkip::EmptyTitle);
    }
    let author_safe = to_folder_name(&author_raw);
    if author_safe.is_empty() {
        return Err(RenameSkip::NoAuthor);
    }
    Ok(format!("[{}] {}", author_safe, title_safe))
}

/// Splits `[Author] The Rest` into `(Some("<Author>"), "<The Rest>")`. Only the
/// very first leading bracket group is considered. `[..]` groups that appear
/// after other text are left for `strip_blocked_brackets`.
fn take_leading_bracket(title: &str) -> (Option<String>, String) {
    let s = title.trim_start();
    if let Some(after_open) = s.strip_prefix('[') {
        if let Some(close) = after_open.find(']') {
            let inner = after_open[..close].trim().to_string();
            if !inner.is_empty() {
                let remaining = after_open[close + 1..].trim_start().to_string();
                return (Some(inner), remaining);
            }
        }
    }
    (None, s.to_string())
}

/// Removes every `[..]` / `(..)` group whose content is classified as useless,
/// keeping everything else intact.
fn strip_blocked_brackets(title: &str, language: Option<&str>, terms: &[String]) -> String {
    let mut out = String::new();
    let mut i = 0;
    while i < title.len() {
        let ch = title[i..].chars().next().expect("in-bounds char");
        let (open, close) = match ch {
            '[' => ('[', ']'),
            '(' => ('(', ')'),
            _ => {
                out.push(ch);
                i += ch.len_utf8();
                continue;
            }
        };
        if let Some(rel) = title[i + ch.len_utf8()..].find(close) {
            let content = &title[i + ch.len_utf8()..i + ch.len_utf8() + rel];
            let consumed = ch.len_utf8() + rel + 1;
            if is_blocked(content, language, terms) {
                i += consumed;
                continue;
            }
            out.push(open);
            out.push_str(content);
            out.push(close);
            i += consumed;
            continue;
        }
        out.push(ch);
        i += ch.len_utf8();
    }
    out
}

/// Whether `inner` (text inside one bracket group) is a useless tag.
fn is_blocked(inner: &str, language: Option<&str>, terms: &[String]) -> bool {
    let lower = inner.trim().to_lowercase();
    if lower.is_empty() {
        return true;
    }
    if language.is_some_and(|l| lower == l.trim().to_lowercase()) {
        return true;
    }
    // Tokenize on any non-alphanumeric separator; CJK counts as alphanumeric so
    // `dl版` stays a single token while `AI-Generated` splits into two words.
    let tokens: Vec<String> = lower
        .split(|c: char| !c.is_alphanumeric())
        .filter(|s| !s.is_empty())
        .map(|s| s.to_string())
        .collect();
    let joined = tokens.join(" ");
    terms.iter().any(|t| {
        let t = t.trim().to_lowercase();
        if t.is_empty() {
            return false;
        }
        if t.contains(' ') {
            joined.contains(&t)
        } else if t.chars().count() >= 5 {
            lower == t || tokens.iter().any(|tok| tok.starts_with(&t))
        } else {
            lower == t || tokens.iter().any(|tok| tok == &t)
        }
    })
}

/// Sanitizes a name for use as a folder basename: keeps alphanumerics (incl.
/// CJK), `- . space`, replaces every other character with `_`, then converts the
/// leftover underscores to spaces and collapses runs of spaces.
fn to_folder_name(name: &str) -> String {
    let mut buf = String::with_capacity(name.len());
    for c in name.chars() {
        if c.is_alphanumeric() || matches!(c, '-' | '_' | '.' | ' ') {
            buf.push(c);
        } else {
            buf.push('_');
        }
    }
    buf.replace('_', " ")
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn r<'a>(title: &str, artist: Option<&str>, language: Option<&str>) -> Result<String, RenameSkip> {
        plan_rename(title, artist, language, &default_filter_terms())
    }

    #[test]
    fn gid_parsing() {
        assert_eq!(parse_old_folder_name("1234567-Title").map(|(g, _)| g), Some(1234567));
        assert_eq!(parse_old_folder_name("12345678-Hi").map(|(g, _)| g), Some(12345678));
        assert!(parse_old_folder_name("Default").is_none());
        assert!(parse_old_folder_name("12-X").is_none(), "too-short gid is ignored");
        assert!(parse_old_folder_name("").is_none());
        assert!(parse_old_folder_name("1234567-Dir/Sub").map(|(g, _)| g).is_some());
    }

    #[test]
    fn author_priority() {
        // Leading bracket wins over metadata.
        assert_eq!(r("[Yom] Shopping Day", Some("fakeartist"), None).unwrap(), "[Yom] Shopping Day");
        // No bracket -> metadata artist.
        assert_eq!(r("Shopping Day", Some("Hoshizora Sora"), None).unwrap(), "[Hoshizora Sora] Shopping Day");
        // Neither -> skipped.
        assert_eq!(r("Shopping Day", None, None), Err(RenameSkip::NoAuthor));
    }

    #[test]
    fn leading_language_bracket_is_not_author() {
        // `[Chinese] Title` has no real author; metadata supplies it.
        let name = r("[Chinese] First Love", Some("Yom") , None).unwrap();
        assert_eq!(name, "[Yom] First Love");
    }

    #[test]
    fn strips_useless_tags() {
        assert_eq!(
            r("[Yom] Title [Chinese] [AI Generated] [Patreon]", None, None).unwrap(),
            "[Yom] Title"
        );
        assert_eq!(
            r("Title (CHN) [translated]", Some("Foo"), None).unwrap(),
            "[Foo] Title"
        );
        assert_eq!(
            r("Title [English] [DL版]", Some("Anonymous"), None).unwrap(),
            "[Anonymous] Title"
        );
    }

    #[test]
    fn language_metadata_removes_matching_bracket() {
        assert_eq!(
            r("Koi [Chinese] Extra", Some("Foo"), Some("chinese")).unwrap(),
            "[Foo] Koi Extra"
        );
        // A stray non-language bracket is preserved (decorative parentheses too).
        assert_eq!(
            r("[Foo] Title [Series Name]", None, None).unwrap(),
            "[Foo] Title Series Name"
        );
    }

    #[test]
    fn underscore_becomes_space() {
        assert_eq!(
            r("[Foo] My_Series_ /_v1_", None, None).unwrap(),
            "[Foo] My Series v1"
        );
    }

    #[test]
    fn idempotent() {
        let first = r("[Yom] Shopping Day", None, None).unwrap();
        let second = r("[Yom] Shopping Day", None, None).unwrap();
        assert_eq!(first, second);
        assert_eq!(first, "[Yom] Shopping Day");
    }

    #[test]
    fn empty_title_after_filter_skips() {
        assert_eq!(r("[Chinese] [AI Generated]", Some("Foo"), None), Err(RenameSkip::EmptyTitle));
    }

    #[test]
    fn custom_terms_work() {
        let custom = vec!["mycustomtag".to_string()];
        let name = plan_rename("[Foo] Title [MyCustomTag]", None, None, &custom).unwrap();
        assert_eq!(name, "[Foo] Title");
        // Default terms do not know it, so the tag is kept.
        let name2 = plan_rename("[Foo] Title [MyCustomTag]", None, None, &default_filter_terms()).unwrap();
        assert_eq!(name2, "[Foo] Title MyCustomTag");
    }
}
